# 

同一个 Animatable 对象，当一个动画进行中时，另一个动画开始执行，会停止上一个动画。

当动画被意外停止，会在协程中抛一个 `CancellationException`

```kotlin
val anim = remember {  
    Animatable(0.dp, Dp.VectorConverter)  
}  
val decay = remember {  
    exponentialDecay<Dp>()  
}  
LaunchedEffect(Unit) {  
    delay(1000)  
    try {  
	    anim.animateDecay(100.dp, decay)  
	} catch (e : CancellationException) {  
	    Log.d(TAG, "first onexception")  
	}
}  
  
LaunchedEffect(Unit) {  
    delay(1500)  
    anim.animateDecay((-1000).dp, decay)  
}  
  
Box(  
    modifier = Modifier  
        .padding(0.dp, anim.value, 0.dp, 0.dp)  
        .size(100.dp)  
        .background(Color.Green)  
)
```

例如上面的代码，有两个协程，延迟的时间不同，第二个动画执行时，会打断第一个 `animateDecay` 动画，抛出 `CancellationException`

